export const  GET_BOOKS = "GET_BOOKS"
export const  UPDATE_BOOKS = "UPDATE_BOOKS"
export const  ADD_TO_CART = "ADD_TO_CART"
export const  EMPTY_CART = "EMPTY_CART"
export const  CREATE_ORDER = "CREATE_ORDER"
export const  LOAD_BOOKS = "LOAD_BOOKS"
export const  CREATE_ADDRESS = "CREATE_ADDRESS"
export const  UPDATE_ADDRESS = "UPDATE_ADDRESS"